### ISSUE TITLE
Select one only option

### ISSUE THREAD

**Issue by davidlcarrascal** [Shamsiddin/SHMultipleSelect#3]
How can I do it to select only one option and do not have multiple selections?

**Comment by Shamsiddin** [comment]
As SHMultipleSelect is multiple selection component it doesn't support radio button functionality.

**Comment by davidlcarrascal** [comment]
Ok thanks! Do you know any pods to do it?

**Comment by Shamsiddin** [comment]
Have you looked at cocoacontrols.com? https://www.cocoacontrols.com/search?q=radio
